# Task 1.2. Use https://mvnrepository.com/artifact/com.h2database/h2 as a Data Source.
app:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"
    jdbc-url: ${app.datasource.url} # for Hikari
    username: "sa"
    password: ""
    enabled: true

spring:
  jpa:
    show-sql: true
    database-platform: "org.hibernate.dialect.H2Dialect"
    properties:
      hibernate:
        "globally_quoted_identifiers": "true" # Address a conflict for 'order' entity
  h2:
    console:
      enabled: true


# Task 4.5. Only 2 endpoints (/health and custom endpoint above) should be exposed.
# Apply these changes for both environments (local and dev) by using a base configuration file.
management:
  endpoints:
    web:
      exposure:
        include: health, appinfo