version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: local_postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pg:/var/lib/postgresql/data
volumes:
  local_pg: