info-statistics: process.cpu.usage


management.endpoints.web.exposure.include: "info,health,metrics"


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        "globally_quoted_identifiers": true
  sql:
    init:
      mode: always
      continue-on-error: false
      #schema-locations: classpath*:org/springframework/security/core/userdetails/jdbc/users.ddl - the default schema is not suitable for postresql
