spring:
  sql.init.mode: always # in our case, not needed since embedded db is in use
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # schema is predefined
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        "globally_quoted_identifiers": "true"
        format-sql: true

  h2:
    console.enabled: true
  mvc:
    static-path-pattern: /swagger*

springdoc:
  swagger-ui:
    path: /swagger-ui.html